# Generated by Django 4.1.7 on 2023-03-31 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='Principal_blog',
        ),
    ]
